name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  go:
    name: Go tests and formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4.4.0

      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff  # v5.6.0
        with:
          go-version-file: 'go.mod'

      - run: go vet ./...

      - run: go test ./... -short

      - name: gofmt
        run: |
          files=$(gofmt -l .)
          if [ -n "$files" ]; then
            echo "gofmt needs to run on:"
            echo "$files"
            exit 1
          fi

      - name: Race detector
        run: go test ./... -short -race
